//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class DuDauKyCongNo
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> TaiKhoanId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<decimal> DuNo { get; set; }
        public Nullable<decimal> DuNoVND { get; set; }
        public Nullable<decimal> DuCo { get; set; }
        public Nullable<decimal> DuCoVND { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
