//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonGTGT
    {
        public int Id { get; set; }
        public Nullable<int> PhieuNhapId { get; set; }
        public Nullable<int> PhieuXuatId { get; set; }
        public Nullable<int> PhieuChiId { get; set; }
        public Nullable<int> PhieuKeToanId { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> MauBC { get; set; }
        public Nullable<int> LoaiThue { get; set; }
        public string MaCt { get; set; }
        public Nullable<System.DateTime> NgayCt { get; set; }
        public string SoCt { get; set; }
        public Nullable<System.DateTime> NgayCt0 { get; set; }
        public string SoCt0 { get; set; }
        public string SoSeri0 { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string KhachHangUd { get; set; }
        public string KhachHangNm { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<int> KhoId { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public string VatTu { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaVND { get; set; }
        public Nullable<decimal> Tien { get; set; }
        public Nullable<decimal> TienVND { get; set; }
        public Nullable<decimal> Thue { get; set; }
        public Nullable<decimal> ThueVND { get; set; }
        public Nullable<int> MaThue { get; set; }
        public Nullable<decimal> ThueSuat { get; set; }
        public Nullable<int> TkThue { get; set; }
        public Nullable<int> TkDu { get; set; }
        public string CucThue { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaTuDo { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<int> MaTD01 { get; set; }
        public Nullable<int> MaTD02 { get; set; }
        public Nullable<int> MaTD03 { get; set; }
        public Nullable<bool> IsPhieu { get; set; }
        public Nullable<int> MauHDId { get; set; }
        public string MauHDUd { get; set; }
        public string KyHieuMauHD { get; set; }
        public Nullable<int> DieuChinhThueTNDNId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual PhieuChi PhieuChi { get; set; }
        public virtual PhieuKeToan PhieuKeToan { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
