//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonMuaHang
    {
        public int Id { get; set; }
        public Nullable<int> PhieuNhapId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> GhiNoTK { get; set; }
        public Nullable<decimal> Tien { get; set; }
        public Nullable<decimal> TienVND { get; set; }
        public Nullable<decimal> PsNo { get; set; }
        public Nullable<decimal> PsNoVND { get; set; }
        public Nullable<decimal> PsCo { get; set; }
        public Nullable<decimal> PsCoVND { get; set; }
        public string NhomDk { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<int> BoPhanHTId { get; set; }
        public Nullable<int> VatTuId1 { get; set; }
        public Nullable<int> MaTD01 { get; set; }
        public Nullable<System.DateTime> NgayTD01 { get; set; }
        public Nullable<decimal> SoLuongTD01 { get; set; }
        public string GhiChuTD01 { get; set; }
        public Nullable<int> MaTD02 { get; set; }
        public Nullable<System.DateTime> NgayTD02 { get; set; }
        public Nullable<decimal> SoLuongTD02 { get; set; }
        public string GhiChuTD02 { get; set; }
        public Nullable<int> MaTD03 { get; set; }
        public Nullable<System.DateTime> NgayTD03 { get; set; }
        public Nullable<decimal> SoLuongTD03 { get; set; }
        public string GhiChuTD03 { get; set; }
        public Nullable<int> DieuChinhThueTNDNId { get; set; }
        public string ConnectAEDichVu { get; set; }
        public Nullable<int> DmTapHopChiPhiId { get; set; }
        public Nullable<int> CongTrinhId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
