//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonGTGT = new HashSet<HoaDonGTGT>();
        }
    
        public int Id { get; set; }
        public string KhachHangUd { get; set; }
        public string KhachHangNm { get; set; }
        public string KhachHangNm2 { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public string DiaChi { get; set; }
        public string DoiTac { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<int> TkNgamDinh { get; set; }
        public Nullable<int> TkKho { get; set; }
        public Nullable<int> TkChietKhau { get; set; }
        public Nullable<int> HanTtNgamDinh { get; set; }
        public Nullable<bool> IsConGiaoDich { get; set; }
        public Nullable<decimal> Sodu { get; set; }
        public string DienThoai { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string TkNganHang { get; set; }
        public string TenNganHang { get; set; }
        public string TinhThanh { get; set; }
        public string GhiChu { get; set; }
        public string MaTd1 { get; set; }
        public Nullable<System.DateTime> NgayTd1 { get; set; }
        public Nullable<decimal> SoLuongTd1 { get; set; }
        public string GhiChuTd1 { get; set; }
        public string MaTd2 { get; set; }
        public Nullable<System.DateTime> NgayTd2 { get; set; }
        public Nullable<decimal> SoLuongTd2 { get; set; }
        public string GhiChuTd2 { get; set; }
        public string MaTd3 { get; set; }
        public Nullable<System.DateTime> NgayTd3 { get; set; }
        public Nullable<decimal> SoLuongTd3 { get; set; }
        public string GhiChuTd3 { get; set; }
        public string DiaDiemGiao { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> NhomKhachHang1 { get; set; }
        public Nullable<int> NhomKhachHang2 { get; set; }
        public Nullable<int> NhomKhachHang3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonGTGT> HoaDonGTGT { get; set; }
    }
}
