//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgoaiTe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NgoaiTe()
        {
            this.TyGiaNgoaiTe = new HashSet<TyGiaNgoaiTe>();
        }
    
        public int Id { get; set; }
        public string NgoaiTeUd { get; set; }
        public string NgoaiTeNm { get; set; }
        public string NgoaiTeNm2 { get; set; }
        public string Comma { get; set; }
        public string DvtienLe { get; set; }
        public string Dvtien { get; set; }
        public string Chan { get; set; }
        public string Comma2 { get; set; }
        public string DvtienLe2 { get; set; }
        public string Dvtien2 { get; set; }
        public string Chan2 { get; set; }
        public Nullable<decimal> So { get; set; }
        public string ChuAnh { get; set; }
        public string ChuViet { get; set; }
        public Nullable<int> DocSoLe { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TyGiaNgoaiTe> TyGiaNgoaiTe { get; set; }
    }
}
