//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuChi()
        {
            this.HoaDonGTGT1 = new HashSet<HoaDonGTGT>();
            this.PhieuChiCT = new HashSet<PhieuChiCT>();
            this.SoCai = new HashSet<SoCai>();
        }
    
        public int Id { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> GiaoDichId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string NguoiNhan { get; set; }
        public Nullable<int> GhiNoTkId { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string SoPhieu { get; set; }
        public string QuyenSoId { get; set; }
        public string ChungTu { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public Nullable<decimal> TyGiaGS { get; set; }
        public Nullable<int> HoaDonGTGT { get; set; }
        public Nullable<int> TkThue { get; set; }
        public Nullable<decimal> Tien { get; set; }
        public Nullable<decimal> TienVND { get; set; }
        public Nullable<decimal> TienThue { get; set; }
        public Nullable<decimal> TienThueVND { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongTienVND { get; set; }
        public Nullable<int> RefId { get; set; }
        public string TenNganHang { get; set; }
        public string SoTaiKhoan { get; set; }
        public string TenTinhThanh { get; set; }
        public string TenKhachHang { get; set; }
        public string DiaChi { get; set; }
        public string SoTaiKhoan2 { get; set; }
        public string TenNganHang2 { get; set; }
        public string DiaChi2 { get; set; }
        public string NoiDung { get; set; }
        public string CamKet { get; set; }
        public Nullable<int> MucDich { get; set; }
        public Nullable<int> HinhThuc { get; set; }
        public Nullable<int> PhiTrong { get; set; }
        public Nullable<int> PhiNgoai { get; set; }
        public string DiaChiKH { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<bool> IsSuaTien { get; set; }
        public Nullable<bool> IsTaoTuDong { get; set; }
        public Nullable<bool> IsPostSC { get; set; }
        public Nullable<int> PhieuNhapId { get; set; }
        public string PhieuNhapUd { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string BankAccountNumber { get; set; }
        public string DienGiai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonGTGT> HoaDonGTGT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuChiCT> PhieuChiCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoCai> SoCai { get; set; }
    }
}
