//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhapCT
    {
        public int Id { get; set; }
        public Nullable<int> PhieuNhapId { get; set; }
        public Nullable<int> VatTuId { get; set; }
        public Nullable<int> KhoId { get; set; }
        public Nullable<System.DateTime> NgayLo { get; set; }
        public string SoLo { get; set; }
        public Nullable<decimal> TonKho { get; set; }
        public Nullable<decimal> SoLuongBuy { get; set; }
        public Nullable<decimal> SoLuongPlus { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> SoLuongConLai { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaVND { get; set; }
        public Nullable<decimal> Tien { get; set; }
        public Nullable<decimal> TienVND { get; set; }
        public Nullable<decimal> TienTt { get; set; }
        public Nullable<decimal> TienTtVND { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<decimal> GiaVonVND { get; set; }
        public Nullable<decimal> TienVon { get; set; }
        public Nullable<decimal> TienVonVND { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<decimal> ChiPhiVND { get; set; }
        public Nullable<decimal> ThueNk { get; set; }
        public Nullable<decimal> ThueNkVND { get; set; }
        public Nullable<decimal> TyLeCk { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> ChietKhauVND { get; set; }
        public Nullable<int> TkHbtl { get; set; }
        public Nullable<int> TkKho { get; set; }
        public Nullable<int> TkGiaVon { get; set; }
        public Nullable<int> TkChietKhau { get; set; }
        public Nullable<int> GhiNoTK { get; set; }
        public Nullable<bool> IsXuatTraLai { get; set; }
        public Nullable<int> PhieuXuatChiTietId { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public Nullable<int> BoPhanHTId { get; set; }
        public Nullable<int> VatTuId1 { get; set; }
        public Nullable<int> MaTD01 { get; set; }
        public Nullable<System.DateTime> NgayTD01 { get; set; }
        public Nullable<decimal> SoLuongTD01 { get; set; }
        public string GhiChuTD01 { get; set; }
        public Nullable<int> MaTD02 { get; set; }
        public Nullable<System.DateTime> NgayTD02 { get; set; }
        public Nullable<decimal> SoLuongTD02 { get; set; }
        public string GhiChuTD02 { get; set; }
        public Nullable<int> MaTD03 { get; set; }
        public Nullable<System.DateTime> NgayTD03 { get; set; }
        public Nullable<decimal> SoLuongTD03 { get; set; }
        public string GhiChuTD03 { get; set; }
        public Nullable<int> DieuChinhThueTNDNId { get; set; }
        public string ConnectAEVatTu { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
