//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuat
    {
        public int Id { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> GiaoDichId { get; set; }
        public Nullable<int> MauHoaDonId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string NguoiMuaHang { get; set; }
        public string NguoiGiaoHang { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> GhiNoTk { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> BoPhanId { get; set; }
        public string HinhThucTt { get; set; }
        public string SoCt { get; set; }
        public string QuyenSo { get; set; }
        public string SoHd { get; set; }
        public string SoSeri { get; set; }
        public Nullable<System.DateTime> NgayHt { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> TiGia { get; set; }
        public Nullable<bool> IsGiaVonDD { get; set; }
        public string NhomHang { get; set; }
        public Nullable<int> MauBC { get; set; }
        public Nullable<int> LoaiThueId { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<decimal> TienVon { get; set; }
        public Nullable<decimal> TienVonVND { get; set; }
        public Nullable<decimal> TienHang { get; set; }
        public Nullable<decimal> TienHangVND { get; set; }
        public Nullable<decimal> TienChietKhau { get; set; }
        public Nullable<decimal> TienChietKhauVND { get; set; }
        public Nullable<decimal> TienHangCk { get; set; }
        public Nullable<decimal> TienHangCkVND { get; set; }
        public Nullable<decimal> ThueVat { get; set; }
        public Nullable<decimal> ThueVatVND { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongTienVND { get; set; }
        public Nullable<int> ThueSuatId { get; set; }
        public Nullable<decimal> ThueSuat { get; set; }
        public Nullable<int> TkThueVat { get; set; }
        public Nullable<int> TkThueVatDu { get; set; }
        public Nullable<int> TkChietKhau { get; set; }
        public Nullable<bool> IsSuaTienThue { get; set; }
        public Nullable<bool> IsSuaTkThue { get; set; }
        public Nullable<bool> IsSuaTienCk { get; set; }
        public Nullable<int> HanTt { get; set; }
        public Nullable<decimal> TienHd { get; set; }
        public Nullable<decimal> TienHdVND { get; set; }
        public Nullable<decimal> TienPhaiTt { get; set; }
        public Nullable<decimal> TienPhaiTtVND { get; set; }
        public Nullable<decimal> ConPhaiTt { get; set; }
        public Nullable<decimal> ConPhaiTtVND { get; set; }
        public Nullable<decimal> TienTt { get; set; }
        public Nullable<decimal> TienTtVND { get; set; }
        public Nullable<bool> IsTatToan { get; set; }
        public Nullable<bool> IsXem { get; set; }
        public Nullable<bool> IsDaIn { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayHopDong { get; set; }
        public string DiaDiemGiao { get; set; }
        public string DiaDiemNhan { get; set; }
        public string SoVanDon { get; set; }
        public Nullable<System.DateTime> NgayVanDon { get; set; }
        public string SoContainer { get; set; }
        public string TenDvvc { get; set; }
        public Nullable<bool> IsSuaHD { get; set; }
        public Nullable<int> MauHDId { get; set; }
        public string MauHDUd { get; set; }
        public string KyHieuMauHD { get; set; }
        public Nullable<bool> IsSuaTien { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<bool> IsAmThue { get; set; }
        public Nullable<bool> IsPostSC { get; set; }
        public Nullable<bool> EInvoice { get; set; }
        public Nullable<System.DateTime> ECreatedDate { get; set; }
        public Nullable<System.DateTime> EModifiedDate { get; set; }
        public string ECreatedBy { get; set; }
        public string TienBangChu { get; set; }
        public Nullable<System.DateTime> EResultDate { get; set; }
        public string EResultBy { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public string TkNganHang { get; set; }
        public string Fax { get; set; }
        public string EResult { get; set; }
        public string SyncError { get; set; }
        public Nullable<bool> IsBoTrongGia { get; set; }
        public string mInvoiceInvoiceAuthId { get; set; }
        public string mInvoiceSovb { get; set; }
        public Nullable<System.DateTime> mInvoiceNgayvb { get; set; }
        public string mInvoiceGhiChu { get; set; }
        public Nullable<bool> IsHuy { get; set; }
        public string ViettelInvoicetransactionID { get; set; }
        public string ViettelInvoicereservationCode { get; set; }
        public string CA2HoaDonID { get; set; }
        public string CA2KeyTichHop { get; set; }
        public string CA2MaTraCuu { get; set; }
        public string HoaDonVietInvoiceAuthId { get; set; }
        public string ViettelInvoiceSupplierTaxCode { get; set; }
        public string ViettelInvoiceTransactionUuid { get; set; }
        public string ConnectAE { get; set; }
        public Nullable<bool> IsSuaTienSauThue { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
