//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuChiCT
    {
        public int Id { get; set; }
        public Nullable<int> PhieuChiId { get; set; }
        public Nullable<int> HoaDonDichVuId { get; set; }
        public Nullable<int> HoaDonChiId { get; set; }
        public string SoCt { get; set; }
        public Nullable<System.DateTime> NgayHd { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public Nullable<int> GhiNoTk { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<decimal> TienTrenHd { get; set; }
        public Nullable<decimal> TienTrenHdVND { get; set; }
        public Nullable<decimal> DaTt { get; set; }
        public Nullable<decimal> DaTtVND { get; set; }
        public Nullable<decimal> ConPhaiTt { get; set; }
        public Nullable<decimal> ConPhaiTtVND { get; set; }
        public Nullable<decimal> PsNo { get; set; }
        public Nullable<decimal> PsNoVND { get; set; }
        public Nullable<int> LoaiThue { get; set; }
        public Nullable<decimal> ThueSuat { get; set; }
        public Nullable<decimal> Thue { get; set; }
        public Nullable<decimal> ThueVND { get; set; }
        public Nullable<decimal> ThanhToan { get; set; }
        public Nullable<decimal> ThanhToanVND { get; set; }
        public Nullable<decimal> ThanhToanQd { get; set; }
        public Nullable<decimal> TyGiaGS { get; set; }
        public string DienGiai { get; set; }
        public string DienGiai2 { get; set; }
        public Nullable<decimal> TienHt { get; set; }
        public string SoHd { get; set; }
        public string SoSeri { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<int> BoPhanHTId { get; set; }
        public Nullable<int> VatTuId1 { get; set; }
        public Nullable<int> MaTD01 { get; set; }
        public Nullable<System.DateTime> NgayTD01 { get; set; }
        public Nullable<decimal> SoLuongTD01 { get; set; }
        public string GhiChuTD01 { get; set; }
        public Nullable<int> MaTD02 { get; set; }
        public Nullable<System.DateTime> NgayTD02 { get; set; }
        public Nullable<decimal> SoLuongTD02 { get; set; }
        public string GhiChuTD02 { get; set; }
        public Nullable<int> MaTD03 { get; set; }
        public Nullable<System.DateTime> NgayTD03 { get; set; }
        public Nullable<decimal> SoLuongTD03 { get; set; }
        public string GhiChuTD03 { get; set; }
        public Nullable<int> MauHDId { get; set; }
        public string MauHDUd { get; set; }
        public string KiHieuMauHD { get; set; }
        public Nullable<int> DieuChinhThueTNDNId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
    
        public virtual PhieuChi PhieuChi { get; set; }
    }
}
