//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuThu()
        {
            this.PhieuThuCT = new HashSet<PhieuThuCT>();
            this.SoCai = new HashSet<SoCai>();
        }
    
        public int Id { get; set; }
        public string LoaiPhieu { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<int> GiaoDichId { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public string NguoiNop { get; set; }
        public Nullable<int> GhiNoTkId { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string SoPhieu { get; set; }
        public string QuyenSoId { get; set; }
        public string ChungTu { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongTienVND { get; set; }
        public Nullable<int> RefId { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public Nullable<bool> IsSuaTien { get; set; }
        public Nullable<bool> IsTaoTuDong { get; set; }
        public Nullable<bool> IsPostSC { get; set; }
        public Nullable<int> PhieuXuatId { get; set; }
        public string PhieuXuatUd { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public string BankAccountNumber { get; set; }
        public string DienGiai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuThuCT> PhieuThuCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoCai> SoCai { get; set; }
    }
}
