//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int Id { get; set; }
        public string TaiKhoanUd { get; set; }
        public string TaiKhoanNm { get; set; }
        public string TaiKhoanNm1 { get; set; }
        public string TaiKhoanNm2 { get; set; }
        public string TaiKhoanNm3 { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<int> TaiKhoanParentId { get; set; }
        public Nullable<bool> IsTKCongNo { get; set; }
        public Nullable<bool> IsTKSoCai { get; set; }
        public Nullable<int> BacTK { get; set; }
        public Nullable<bool> IsBacCuoi { get; set; }
        public Nullable<int> NhomTieuKhoanId { get; set; }
        public Nullable<int> NhomTaiKhoanId { get; set; }
        public Nullable<int> TGGSNo { get; set; }
        public Nullable<int> TGGSCo { get; set; }
        public Nullable<bool> IsDk { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<int> Loai { get; set; }
        public Nullable<int> TieuKhoanId { get; set; }
        public Nullable<bool> IsTKVatTu { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
