//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BORO_EACCOUNTING_WEB_V1Entities : DbContext
    {
        public BORO_EACCOUNTING_WEB_V1Entities()
            : base("name=BORO_EACCOUNTING_WEB_V1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoPhanHT> BoPhanHT { get; set; }
        public virtual DbSet<CongTrinh> CongTrinh { get; set; }
        public virtual DbSet<ChiNhanh> ChiNhanh { get; set; }
        public virtual DbSet<DieuChinhThueTNDN> DieuChinhThueTNDN { get; set; }
        public virtual DbSet<DMChung> DMChung { get; set; }
        public virtual DbSet<DmMaPhi> DmMaPhi { get; set; }
        public virtual DbSet<DmTruongTuDo> DmTruongTuDo { get; set; }
        public virtual DbSet<DuDauKyCongNo> DuDauKyCongNo { get; set; }
        public virtual DbSet<HoaDonGTGT> HoaDonGTGT { get; set; }
        public virtual DbSet<HoaDonMuaHang> HoaDonMuaHang { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<Kho> Kho { get; set; }
        public virtual DbSet<NgoaiTe> NgoaiTe { get; set; }
        public virtual DbSet<NhomKhachHang> NhomKhachHang { get; set; }
        public virtual DbSet<NhomVatTu> NhomVatTu { get; set; }
        public virtual DbSet<PhanBoChietKhauThuongMai> PhanBoChietKhauThuongMai { get; set; }
        public virtual DbSet<PhanBoChiPhi> PhanBoChiPhi { get; set; }
        public virtual DbSet<PhanBoThueNk> PhanBoThueNk { get; set; }
        public virtual DbSet<PhieuChi> PhieuChi { get; set; }
        public virtual DbSet<PhieuChiCT> PhieuChiCT { get; set; }
        public virtual DbSet<PhieuKeToan> PhieuKeToan { get; set; }
        public virtual DbSet<PhieuKeToanCt> PhieuKeToanCt { get; set; }
        public virtual DbSet<PhieuNhap> PhieuNhap { get; set; }
        public virtual DbSet<PhieuNhapCT> PhieuNhapCT { get; set; }
        public virtual DbSet<PhieuNhapKho> PhieuNhapKho { get; set; }
        public virtual DbSet<PhieuNhapKhoCt> PhieuNhapKhoCt { get; set; }
        public virtual DbSet<PhieuThu> PhieuThu { get; set; }
        public virtual DbSet<PhieuThuCT> PhieuThuCT { get; set; }
        public virtual DbSet<PhieuXuat> PhieuXuat { get; set; }
        public virtual DbSet<PhieuXuatDcKho> PhieuXuatDcKho { get; set; }
        public virtual DbSet<PhieuXuatDcKhoCt> PhieuXuatDcKhoCt { get; set; }
        public virtual DbSet<PhieuXuatKho> PhieuXuatKho { get; set; }
        public virtual DbSet<PhieuXuatKhoCt> PhieuXuatKhoCt { get; set; }
        public virtual DbSet<QuyenSo> QuyenSo { get; set; }
        public virtual DbSet<SoCai> SoCai { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoan { get; set; }
        public virtual DbSet<TyGiaNgoaiTe> TyGiaNgoaiTe { get; set; }
        public virtual DbSet<TheKho> TheKho { get; set; }
        public virtual DbSet<VatTu> VatTu { get; set; }
        public virtual DbSet<VuViec> VuViec { get; set; }
    
        public virtual int TongHopHangNhapMuaPreview(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<int> loaiPhieu, string ctuTu, string ctuDen, Nullable<int> vatTu_id, Nullable<int> tkVatTu, Nullable<int> khachHang_id, Nullable<int> vuViec_id, Nullable<int> kho_id, Nullable<int> taiKhoan_id, Nullable<int> chiNhanh_id, string khachHang_ud, string vuViec_ud, string kho_ud, string taiKhoan_ud, string vatTu_ud, string tkVatTu_ud, Nullable<int> nhomVatTu01_id, Nullable<int> nhomVatTu02_id, Nullable<int> nhomVatTu03_id, string nhomVatTu01_ud, string nhomVatTu02_ud, string nhomVatTu03_ud)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var loaiPhieuParameter = loaiPhieu.HasValue ?
                new ObjectParameter("LoaiPhieu", loaiPhieu) :
                new ObjectParameter("LoaiPhieu", typeof(int));
    
            var ctuTuParameter = ctuTu != null ?
                new ObjectParameter("CtuTu", ctuTu) :
                new ObjectParameter("CtuTu", typeof(string));
    
            var ctuDenParameter = ctuDen != null ?
                new ObjectParameter("CtuDen", ctuDen) :
                new ObjectParameter("CtuDen", typeof(string));
    
            var vatTu_idParameter = vatTu_id.HasValue ?
                new ObjectParameter("VatTu_id", vatTu_id) :
                new ObjectParameter("VatTu_id", typeof(int));
    
            var tkVatTuParameter = tkVatTu.HasValue ?
                new ObjectParameter("TkVatTu", tkVatTu) :
                new ObjectParameter("TkVatTu", typeof(int));
    
            var khachHang_idParameter = khachHang_id.HasValue ?
                new ObjectParameter("KhachHang_id", khachHang_id) :
                new ObjectParameter("KhachHang_id", typeof(int));
    
            var vuViec_idParameter = vuViec_id.HasValue ?
                new ObjectParameter("VuViec_id", vuViec_id) :
                new ObjectParameter("VuViec_id", typeof(int));
    
            var kho_idParameter = kho_id.HasValue ?
                new ObjectParameter("Kho_id", kho_id) :
                new ObjectParameter("Kho_id", typeof(int));
    
            var taiKhoan_idParameter = taiKhoan_id.HasValue ?
                new ObjectParameter("TaiKhoan_id", taiKhoan_id) :
                new ObjectParameter("TaiKhoan_id", typeof(int));
    
            var chiNhanh_idParameter = chiNhanh_id.HasValue ?
                new ObjectParameter("ChiNhanh_id", chiNhanh_id) :
                new ObjectParameter("ChiNhanh_id", typeof(int));
    
            var khachHang_udParameter = khachHang_ud != null ?
                new ObjectParameter("KhachHang_ud", khachHang_ud) :
                new ObjectParameter("KhachHang_ud", typeof(string));
    
            var vuViec_udParameter = vuViec_ud != null ?
                new ObjectParameter("VuViec_ud", vuViec_ud) :
                new ObjectParameter("VuViec_ud", typeof(string));
    
            var kho_udParameter = kho_ud != null ?
                new ObjectParameter("Kho_ud", kho_ud) :
                new ObjectParameter("Kho_ud", typeof(string));
    
            var taiKhoan_udParameter = taiKhoan_ud != null ?
                new ObjectParameter("TaiKhoan_ud", taiKhoan_ud) :
                new ObjectParameter("TaiKhoan_ud", typeof(string));
    
            var vatTu_udParameter = vatTu_ud != null ?
                new ObjectParameter("VatTu_ud", vatTu_ud) :
                new ObjectParameter("VatTu_ud", typeof(string));
    
            var tkVatTu_udParameter = tkVatTu_ud != null ?
                new ObjectParameter("TkVatTu_ud", tkVatTu_ud) :
                new ObjectParameter("TkVatTu_ud", typeof(string));
    
            var nhomVatTu01_idParameter = nhomVatTu01_id.HasValue ?
                new ObjectParameter("NhomVatTu01_id", nhomVatTu01_id) :
                new ObjectParameter("NhomVatTu01_id", typeof(int));
    
            var nhomVatTu02_idParameter = nhomVatTu02_id.HasValue ?
                new ObjectParameter("NhomVatTu02_id", nhomVatTu02_id) :
                new ObjectParameter("NhomVatTu02_id", typeof(int));
    
            var nhomVatTu03_idParameter = nhomVatTu03_id.HasValue ?
                new ObjectParameter("NhomVatTu03_id", nhomVatTu03_id) :
                new ObjectParameter("NhomVatTu03_id", typeof(int));
    
            var nhomVatTu01_udParameter = nhomVatTu01_ud != null ?
                new ObjectParameter("NhomVatTu01_ud", nhomVatTu01_ud) :
                new ObjectParameter("NhomVatTu01_ud", typeof(string));
    
            var nhomVatTu02_udParameter = nhomVatTu02_ud != null ?
                new ObjectParameter("NhomVatTu02_ud", nhomVatTu02_ud) :
                new ObjectParameter("NhomVatTu02_ud", typeof(string));
    
            var nhomVatTu03_udParameter = nhomVatTu03_ud != null ?
                new ObjectParameter("NhomVatTu03_ud", nhomVatTu03_ud) :
                new ObjectParameter("NhomVatTu03_ud", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TongHopHangNhapMuaPreview", tuNgayParameter, denNgayParameter, loaiPhieuParameter, ctuTuParameter, ctuDenParameter, vatTu_idParameter, tkVatTuParameter, khachHang_idParameter, vuViec_idParameter, kho_idParameter, taiKhoan_idParameter, chiNhanh_idParameter, khachHang_udParameter, vuViec_udParameter, kho_udParameter, taiKhoan_udParameter, vatTu_udParameter, tkVatTu_udParameter, nhomVatTu01_idParameter, nhomVatTu02_idParameter, nhomVatTu03_idParameter, nhomVatTu01_udParameter, nhomVatTu02_udParameter, nhomVatTu03_udParameter);
        }
    }
}
