//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class TheKho
    {
        public int Id { get; set; }
        public Nullable<int> PhanBoChiPhiId { get; set; }
        public Nullable<int> PhieuXuatCtId { get; set; }
        public Nullable<int> PhieuNhapKhoCtId { get; set; }
        public Nullable<int> PhieuXuatKhoCtId { get; set; }
        public Nullable<int> PhieuXuatDcKhoCtId { get; set; }
        public Nullable<int> TonKhoId { get; set; }
        public Nullable<int> Ct70Id { get; set; }
        public Nullable<int> Ct13Id { get; set; }
        public Nullable<int> Ct76Id { get; set; }
        public string MaNk { get; set; }
        public Nullable<int> MaGd { get; set; }
        public Nullable<int> PnGiaTb { get; set; }
        public Nullable<int> PxGiaDd { get; set; }
        public Nullable<System.DateTime> NgayHt { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string SoCt { get; set; }
        public string SoSeri { get; set; }
        public string SoDh { get; set; }
        public string SoLo { get; set; }
        public Nullable<System.DateTime> NgayLo { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> Ph11Id { get; set; }
        public Nullable<int> KhonId { get; set; }
        public Nullable<int> KhoId { get; set; }
        public string DienGiai { get; set; }
        public Nullable<int> VuViecId { get; set; }
        public Nullable<int> BoPhanId { get; set; }
        public Nullable<int> GhiNoCoTk { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> TyGia { get; set; }
        public Nullable<int> VatTuId { get; set; }
        public Nullable<int> TkVatTu { get; set; }
        public Nullable<int> TkDoanThu { get; set; }
        public Nullable<int> TkGiaVon { get; set; }
        public Nullable<int> TkTraLai { get; set; }
        public Nullable<int> Nxt { get; set; }
        public Nullable<decimal> CtDc { get; set; }
        public Nullable<decimal> SoLuongNhap { get; set; }
        public Nullable<decimal> SoLuongXuat { get; set; }
        public Nullable<decimal> SoLuongNhap1 { get; set; }
        public Nullable<decimal> SoLuongXuat1 { get; set; }
        public Nullable<decimal> Gia { get; set; }
        public Nullable<decimal> GiaVND { get; set; }
        public Nullable<decimal> Gia1 { get; set; }
        public Nullable<decimal> GiaVND1 { get; set; }
        public Nullable<decimal> TienNhap { get; set; }
        public Nullable<decimal> TienXuat { get; set; }
        public Nullable<decimal> TienNhapVND { get; set; }
        public Nullable<decimal> TienXuatVND { get; set; }
        public Nullable<decimal> Gia0 { get; set; }
        public Nullable<decimal> GiaVND0 { get; set; }
        public Nullable<decimal> Gia01 { get; set; }
        public Nullable<decimal> GiaVND01 { get; set; }
        public Nullable<decimal> Tien0 { get; set; }
        public Nullable<decimal> TienVND0 { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<decimal> ChiPhiVND { get; set; }
        public Nullable<decimal> ThueNk { get; set; }
        public Nullable<decimal> ThueNkVND { get; set; }
        public Nullable<int> TkThueNk { get; set; }
        public Nullable<decimal> Gia2 { get; set; }
        public Nullable<decimal> GiaVND2 { get; set; }
        public Nullable<decimal> Gia21 { get; set; }
        public Nullable<decimal> GiaVND21 { get; set; }
        public Nullable<decimal> Tien2 { get; set; }
        public Nullable<decimal> TienVND2 { get; set; }
        public Nullable<decimal> HanTt { get; set; }
        public Nullable<decimal> CpThueCk { get; set; }
        public Nullable<decimal> ThueSuat { get; set; }
        public Nullable<decimal> Thue { get; set; }
        public Nullable<decimal> ThueVND { get; set; }
        public Nullable<int> TkThueNo { get; set; }
        public Nullable<int> TkThueCo { get; set; }
        public Nullable<decimal> ChietKhau { get; set; }
        public Nullable<decimal> ChietKhauVND { get; set; }
        public Nullable<int> TkChietKhau { get; set; }
        public Nullable<int> ChiNhanhId { get; set; }
        public Nullable<decimal> SoCt0 { get; set; }
        public Nullable<decimal> SoSeri0 { get; set; }
        public Nullable<System.DateTime> NgayCt0 { get; set; }
        public Nullable<int> MaPhiId { get; set; }
        public Nullable<int> MaTD01 { get; set; }
        public Nullable<int> MaTD02 { get; set; }
        public Nullable<int> MaTD03 { get; set; }
        public Nullable<bool> IsNhapThuHoi { get; set; }
        public Nullable<int> BoPhanHTId { get; set; }
        public Nullable<int> VatTuId1 { get; set; }
        public Nullable<bool> IsBoTinhGia { get; set; }
        public Nullable<int> DieuChinhThueTNDNId { get; set; }
        public Nullable<int> DmTapHopChiPhiId { get; set; }
        public Nullable<int> CongTrinhId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
        public Nullable<int> PhieuNhapKhoNoiBoId { get; set; }
        public Nullable<int> PhieuNhapCtId { get; set; }
    
        public virtual PhieuNhapKhoCt PhieuNhapKhoCt { get; set; }
        public virtual PhieuXuatDcKhoCt PhieuXuatDcKhoCt { get; set; }
        public virtual PhieuXuatKhoCt PhieuXuatKhoCt { get; set; }
    }
}
