//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        public int Id { get; set; }
        public string VatTuUd { get; set; }
        public string VatTuNm { get; set; }
        public string VatTuNm2 { get; set; }
        public string DonViTinh { get; set; }
        public string SoQD31 { get; set; }
        public string SoDangKy { get; set; }
        public string HamLuong { get; set; }
        public string CachDung { get; set; }
        public string HangSX { get; set; }
        public string NuocSX { get; set; }
        public Nullable<int> NhaThau { get; set; }
        public Nullable<bool> IsTheoDoiTonKho { get; set; }
        public Nullable<int> CachTinhGia { get; set; }
        public Nullable<int> LoaiVatTu { get; set; }
        public Nullable<int> TkKho { get; set; }
        public Nullable<bool> IsSuaTkKho { get; set; }
        public Nullable<int> TkGiaVon { get; set; }
        public Nullable<int> TkCongNo { get; set; }
        public Nullable<int> TkDoanhThu { get; set; }
        public Nullable<int> TkHangBiTra { get; set; }
        public Nullable<int> TkSpDoDang { get; set; }
        public Nullable<int> TkChenhLechGiaVt { get; set; }
        public Nullable<int> NhomVT1 { get; set; }
        public Nullable<int> NhomVT2 { get; set; }
        public Nullable<int> NhomVT3 { get; set; }
        public Nullable<decimal> SLTonToiThieu { get; set; }
        public Nullable<decimal> SLTonToiDa { get; set; }
        public Nullable<decimal> TyLeDT { get; set; }
        public Nullable<bool> IsTinhLuong { get; set; }
        public string GhiChu { get; set; }
        public string MaTd1 { get; set; }
        public Nullable<System.DateTime> NgayTd1 { get; set; }
        public Nullable<decimal> SoLuongTd1 { get; set; }
        public string GhiChuTd1 { get; set; }
        public string MaTd2 { get; set; }
        public Nullable<System.DateTime> NgayTd2 { get; set; }
        public Nullable<decimal> SoLuongTd2 { get; set; }
        public string GhiChuTd2 { get; set; }
        public string MaTd3 { get; set; }
        public Nullable<System.DateTime> NgayTd3 { get; set; }
        public Nullable<decimal> SoLuongTd3 { get; set; }
        public string GhiChuTd3 { get; set; }
        public Nullable<int> KhoId { get; set; }
        public Nullable<bool> IsKhongTinChiPhiNhanCong { get; set; }
        public Nullable<bool> IsKhongTinhChiPhiChung { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
