//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class VuViec
    {
        public int Id { get; set; }
        public string VuViecUd { get; set; }
        public string VuViecNm { get; set; }
        public string VuViecNm2 { get; set; }
        public Nullable<int> KhachHangId { get; set; }
        public Nullable<int> BPKDId { get; set; }
        public Nullable<int> BPTHId { get; set; }
        public Nullable<System.DateTime> NgayBd { get; set; }
        public Nullable<System.DateTime> NgayKt { get; set; }
        public Nullable<int> NgoaiTeId { get; set; }
        public Nullable<decimal> GiaTriHd { get; set; }
        public Nullable<decimal> TienVND { get; set; }
        public Nullable<int> NhomVuViec1 { get; set; }
        public Nullable<int> NhomVuViec2 { get; set; }
        public Nullable<int> NhomVuViec3 { get; set; }
        public string GhiChu { get; set; }
        public string SoHd { get; set; }
        public Nullable<System.DateTime> NgayHd { get; set; }
        public string NoiDung { get; set; }
        public string ThoiGianKhoiCong { get; set; }
        public Nullable<System.DateTime> NgayBBBG { get; set; }
        public Nullable<System.DateTime> NgayTLHD { get; set; }
        public string MaTd1 { get; set; }
        public Nullable<System.DateTime> NgayTd1 { get; set; }
        public Nullable<decimal> SoLuongTd1 { get; set; }
        public string GhiChuTd1 { get; set; }
        public string MaTd2 { get; set; }
        public Nullable<System.DateTime> NgayTd2 { get; set; }
        public Nullable<decimal> SoLuongTd2 { get; set; }
        public string GhiChuTd2 { get; set; }
        public string MaTd3 { get; set; }
        public Nullable<System.DateTime> NgayTd3 { get; set; }
        public Nullable<decimal> SoLuongTd3 { get; set; }
        public string GhiChuTd3 { get; set; }
        public Nullable<int> LoaiChiPhi { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public Nullable<System.DateTime> LastModificationTime { get; set; }
        public Nullable<System.Guid> LastModifierId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> DeleterId { get; set; }
        public Nullable<System.DateTime> DeletionTime { get; set; }
    }
}
